#! /bin/bash

# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.
if [ -x $HOME/.config/bspwm/dual_monitor_with_laptop_scrip;then
   dual_monitor_with_laptop_script 
fi


### Autostart ###

# Hotkey manager
sxhkd &

# Polybar launch script
$HOME/.config/polybar/launch.sh


### Monitor ###
bspc monitor DP-3 -d 1 2 3 4 5
bspc monitor DP-4 -d 6 7 8 9 0


### Monitor and Desktop Settings ###
bscp config top_padding 32
bscp config bottom_padding 0
bscp config left_padding 0
bscp config reight_padding 0

bspc config border_width         2
bspc config window_gap          10

### Core ###
bscp config click_to_focus

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


### Rules ###
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


